server:
  port: 8080
spring:
  jpa:
    hibernate:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    defer-datasource-initialization: true
  datasource:
    url: ${DWBI_DB}
    driver-class-name: org.postgresql.Driver

  h2:
    console.enabled: true